### ISSUE TITLE
shipping upstream container images

### ISSUE THREAD

**Issue by TomasTomecek** [container-images/container-image-template#1]
The only issue I run into is that we should include `modularitycontainers/<image_name>` in github readme, and maybe even in help files.

**Comment by bkabrda** [comment]
@TomasTomecek is the problem sufficiently solved with https://github.com/bkabrda/container-image-template-dg/commit/d128be654c34f9ac6c5982bd2cfa55627e496f2c or do you think this requires more attention?

**Comment by TomasTomecek** [comment]
yup!
